
package com.polk.vindecoder;

//import java.net.MalformedURLException;
//import java.net.URL;
//import java.util.logging.Logger;
//import javax.xml.namespace.QName;
//
//
///**
// * This class was generated by the JAX-WS RI.
// * JAX-WS RI 2.1.4-b01-
// * Generated source version: 2.1
// * 
// */
//public class VinDecoderService
//    extends Service
//{
//
//    private final static URL VINDECODERSERVICE_WSDL_LOCATION;
//    private final static Logger logger = Logger.getLogger(com.polk.vindecoder.VinDecoderService.class.getName());
//
//    static {
//        URL url = null;
//        try {
//            URL baseUrl;
//            baseUrl = com.polk.vindecoder.VinDecoderService.class.getResource(".");
//            url = new URL(baseUrl, "https://vintelligence3.polk.com/vindecoder/VinDecoderService.wsdl");
//        } catch (MalformedURLException e) {
//            logger.warning("Failed to create URL for the wsdl Location: 'https://vintelligence3.polk.com/vindecoder/VinDecoderService.wsdl', retrying as a local file");
//            logger.warning(e.getMessage());
//        }
//        VINDECODERSERVICE_WSDL_LOCATION = url;
//    }
//
//    public VinDecoderService(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public VinDecoderService() {
//        super(VINDECODERSERVICE_WSDL_LOCATION, new QName("http://webservice.vindecoder.polk.com/", "VinDecoderService"));
//    }
//
//    /**
//     * 
//     * @return
//     *     returns VinDecoder
//     */
//    public VinDecoder getVinDecoderPort() {
//        return super.getPort(new QName("http://webservice.vindecoder.polk.com/", "VinDecoderPort"), VinDecoder.class);
//    }
//
//    /**
//     * 
//     * @param features
//     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns VinDecoder
//     */
//    public VinDecoder getVinDecoderPort(WebServiceFeature... features) {
//        return super.getPort(new QName("http://webservice.vindecoder.polk.com/", "VinDecoderPort"), VinDecoder.class, features);
//    }
//
//}
