
package com.polk.vindecoder;

import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
public interface VinDecoder {


    /**
     * 
     * @param requestedFields
     * @param vinRequest
     * @return
     *     returns java.util.List<com.polk.vindecoder.webservice.clientgen.VinResponse>
     * @throws VinDecoderException
     */
    public List<VinResponse> decodeVin(
        List<VinRequest> vinRequest,
        String requestedFields)
        throws VinDecoderException
    ;

    /**
     * 
     * @param vehicleType
     * @param year
     * @return
     *     returns java.util.List<com.polk.vindecoder.webservice.clientgen.Make>
     * @throws VinDecoderException
     */
    public List<Make> getMakes(
        String year,
        String vehicleType)
        throws VinDecoderException
    ;

    /**
     * 
     * @param vehicleType
     * @param year
     * @param make
     * @return
     *     returns java.util.List<com.polk.vindecoder.webservice.clientgen.Model>
     * @throws VinDecoderException
     */
    public List<Model> getModels(
        String year,
        String make,
        String vehicleType)
        throws VinDecoderException
    ;

    /**
     * 
     * @param requestedFields
     * @param psRequest
     * @return
     *     returns java.util.List<com.polk.vindecoder.webservice.clientgen.VinResponse>
     * @throws VinDecoderException
     */
    public List<VinResponse> getPriceAndSpecData(
        List<PSRequest> psRequest,
        String requestedFields)
        throws VinDecoderException
    ;

    /**
     * 
     * @param requestedFields
     * @param vin
     * @return
     *     returns java.util.List<com.polk.vindecoder.webservice.clientgen.VinResponse>
     * @throws VinDecoderException
     */
    public List<VinResponse> getRvData(
        List<String> vin,
        String requestedFields)
        throws VinDecoderException
    ;

    /**
     * 
     * @param year
     * @param make
     * @return
     *     returns java.util.List<com.polk.vindecoder.webservice.clientgen.VehicleType>
     * @throws VinDecoderException
     */
    public List<VehicleType> getVehicleTypes(
        String year,
        String make)
        throws VinDecoderException
    ;

    /**
     * 
     * @param requestedFields
     * @param modelPattern
     * @return
     *     returns com.polk.vindecoder.webservice.clientgen.VinResponse
     * @throws VinDecoderException
     */
    public VinResponse getVinData(
        String modelPattern,
        String requestedFields)
        throws VinDecoderException
    ;

    /**
     * 
     * @param model
     * @param vehicleType
     * @param year
     * @param make
     * @return
     *     returns java.util.List<com.polk.vindecoder.webservice.clientgen.VinPrefixData>
     * @throws VinDecoderException
     */
    public List<VinPrefixData> getVinPrefixes(
        String year,
        String make,
        String vehicleType,
        String model)
        throws VinDecoderException
    ;

    /**
     * 
     * @param vehicleType
     * @param make
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws VinDecoderException
     */
    public List<String> getYears(
        String make,
        String vehicleType)
        throws VinDecoderException
    ;

}
